<template>
   <div class="spinner-container">
      <div class="loadingio-spinner-rolling-qn8zyohjikk spinner">
         <div class="ldio-0sacktyefyr">
            <div></div>
         </div>
      </div>
   </div>
</template>

<script>
    export default {
        name: "Spinner"
    }
</script>

<style scoped>
   .spinner-container{
      height: 100%;
      width: 100%;
      background-color: lightgray;
      opacity: 0.5;
      position: absolute;
      top: 0;
      right: 0;
      z-index: 99;
   }
   .spinner{
      position: absolute;
      left: 50%;
      top: 50%;
      transform: translate(-50%, -50%);
   }
   @keyframes ldio-0sacktyefyr {
      0% { transform: translate(-50%,-50%) rotate(0deg); }
      100% { transform: translate(-50%,-50%) rotate(360deg); }
   }
   .ldio-0sacktyefyr div {
      position: absolute;
      width: 137.9px;
      height: 137.9px;
      border: 19.7px solid #000000;
      border-top-color: transparent;
      border-radius: 50%;
   }
   .ldio-0sacktyefyr div {
      animation: ldio-0sacktyefyr 1s linear infinite;
      top: 98.5px;
      left: 98.5px
   }
   .loadingio-spinner-rolling-qn8zyohjikk {
      width: 197px;
      height: 197px;
      display: inline-block;
      overflow: hidden;
      background: none;
   }
   .ldio-0sacktyefyr {
      width: 100%;
      height: 100%;
      position: relative;
      transform: translateZ(0) scale(1);
      backface-visibility: hidden;
      transform-origin: 0 0; /* see note above */
   }
   .ldio-0sacktyefyr div { box-sizing: content-box; }
   /* generated by https://loading.io/ */
</style>
